### ISSUE TITLE
Missing isOpen() in SerialPort

### ISSUE THREAD

**Issue by Gamadril** [WICG/serial#100]
SerialPort should have the isOpen() method indicating if the port is open or not.

I have an issue with Chrome (85.0.4183.83) on Mac where this method would be useful.
There is a known problem on Mac that serial ports are listed twice. When I select one of them and call getPorts() I also get the selected port twice. From reported getInfo() object there is no difference between the both (the name is missing in the info). However only one can be used for communication. Calling open() on the second one always throws an error: "NetworkError: Failed to open serial port."
Calling open() again on the same SerialPort object leads to the next error: "Failed to execute 'open' on 'SerialPort': The port is already open."
So I realized that there is actually no way to check if a port is already open or not.

P.S. I can see the described behaviour with the second "broken" port also in Chrome on Windows 10. Chrome reports only one port, but always fails on open() showing the same errors: "NetworkError: Failed to open serial port." and "Failed to execute 'open' on 'SerialPort': The port is already open."

P.P.S. Working with WebUSB I really used to chrome://usb-internals/ and chrome://device-log/. It would be nice if there would be something similar for Web Serial for debugging issues with the serial ports.

**Comment by reillyeon** [comment]
It sounds like there are a number of implementation issues you are trying to work around. Let's focus on those first before making changes to the specified interface. I've filed [issue 1127535](https://bugs.chromium.org/p/chromium/issues/detail?id=1127535) to track diagnosing these issues.

**Comment by reillyeon** [comment]
I am going to close this issue because the underlying reason for this request was to detect a condition which was triggered by an implementation bug. In the current API the `readable` and `writable` attributes will be non-null if the port is opened.

**Comment by HenrikJoreteg** [comment]
@reillyeon I know this is an old, closed issue. But I discovered what I think may be a flaw with relying on the `readable` `writable` attributes: they seem to still be `null` even if you have a serial connection open with this same port in another tab 😅 

It seems like the only solution then is to try to open it and looks for the failed to open because already open error.

**Comment by reillyeon** [comment]
Figuring out how to handle the case where a device is open for exclusive access by another document goes beyond the question of adding an `isOpen()` method. `USBDevice`, for example, has an `opened` attribute but it only reflects the state of the current document.
