### ISSUE TITLE
Allow Allways option for permission prompt

### ISSUE THREAD

**Issue by camilova** [WICG/serial#101]
Hi,

I have a scenario in wich a intraweb application must access serial port to work with a device connected to a serial port on each workstation. The serial device is setted in a fixed virtual COM Port and it is always the same model and vendor for all workstations. The user must grant permission when application wants access the port, so it works very good, but in this environment the application will be closed and opened many times at day, so user must always grant permission after he closes the browser, and sometimes user dont know wich port must be selected (normally first time is setted by IT staff). It would be very usefull for this scenario if there were a option `Allow Always` right like the **camera and mic**, and remember the permission for the **same domain**, so user must grant permission only one time for the same domain and later will not ask for permission and `.getPorts()` will return the previously allowed port. User could have a tiny button on the addressbar like btn for camera permission and may be there can revoke at any time.

It is acctually possible? and could this be an option, would be a good idea?

User experience is reduced due frecuently permission prompts.

**Comment by reillyeon** [comment]
The intent of the `getPorts()` method is to do precisely this, but there are technical limitations (which vary by platform) to whether or not the browser can tell at the start of a new session that the ports it currently sees are the "same" as the port selected by the user in the last session.

In the prototype Chromium implementation on Windows this should always work while on other operating systems a USB-based virtual COM port with a serial number is required.

**Comment by camilova** [comment]
thanks for reply. I forgot to say that I'm working now under Linux with Brave browser.
Then should I thing that in future releases may be it will work right this? or do you think it will be very difficult to get this behaviour? Im thinking now if I better write an agent application to make the bridge...

When you say the "same" do you mean the same device or the same port name? because if it remembers the same "port name" would be enought for my use case due virtual COM port is setted to a fixed number, for example COM 15, but may be it isnt the best way to "remember" what the user previously alowed.
Do you know if actually is there a way to turn off the user prompt and get the port without user interaction? I know it kills security but maybe a flag?

thanks in advance.

**Comment by reillyeon** [comment]
In Chromium-based browsers on Linux based on 86.0.4210.2 or later port permissions should be remembered for any USB device which has a serial number and so calling `getPorts()` will return connected devices that were selected during a previous session.

I mean the same device, not the same port name. On some platforms these are the same thing. For example on Windows COM port numbers are persistent. We don't actually record that COM port number but the "device instance ID" which is based on many properties of the device, sufficient to make it stable across reboots and disconnecting and reconnecting the device. On Linux however the port name is assigned sequentially based on the order in which USB devices are enumerated and so there is go guarantee that /dev/ttyUSB0 remains the same device over time. Only if we can also fetch a serial number from the device (this is a standard USB device property) do we remember the device later.

[Chromium issue 1001242](https://crbug.com/1001242) tracks adding enterprise policy options to allow administrators to identify devices that a page should be able to access without user interaction.

**Comment by camilova** [comment]
thank you! I have installed `chrome-beta` based on version 86.0.4240.68 and tested, it works! it remembers the device, just what I wanted. I have tested on linux, but should be same on windows.
