### ISSUE TITLE
Need method to break/terminate reader

### ISSUE THREAD

**Issue by radio-miskovice** [WICG/serial#112]
Hello, I am not the first one having the following problem, did not find any solution (by searching in StackOverflow.com and Google Search) and I think that its nature justifies that it be addressed in the Serial API.

*Situation:*

- **application:** running in Chrome browser, uses serial device as peripheral to send data out and to receive random external events
- **serial device**, two-way communication. Receives data or commands from the app, reports back either required response, or event data. Origin of the event is external and it is random (unpredictable) from the application point of view.
- **user:** works with the application. At any moment user may decide to disconnect the port and/or close the application.

Objects:

`serialPort:` *SerialPort* object, opened
`serialPort.readable:` _ReadableStream_, open (not null nor undefined)
`reader` : _Reader_ object returned by `serialPort.readable.getReader()`

*Problem:*

- The application monitors the port in an infinite loop, with something like `{ value, done } = await reader.read()` at its core.
- Due to the fact that incoming data (events) are random, the app cannot determine whether it will read any more data or not
- when the user decides to disconnect or shutdown, the application should close the serial port.
- However, `serialPort.close()` will throw exception because `serialPort.readable` stream is locked by `reader`
- `reader.releaseLock()` will throw exception, because the reader is "busy" - it is assumed it has to receive some data because `reader.read()` call is in progress.
- As consequence of the above, there is no way to close the port - effectively, `serialPort` is in deadlock.

This would not matter in case when the app is terminated - closing Chrome window, reloading the page, loading another URL. In this case port will be somehow closed by Chrome and can be reused by another application.

However, if, for whatever reason, the app kept running but needed to close the port, it would be impossible.

*Possible solutions*:

1. **BREAK SOLUTION** Add a `SerialPort` method (e.g. `break()`) that would cause exception or other condition in `Reader` so that it can either throw exception or return `{ done: true, ... }`, making it possible to leave the infinite reading loop. I think exception would be more desirable here, but it's up to the designers to decide.  At the same time, the resulting condition should leave the port open and `serialPort.readable` still valid and ready for further use, including creating a new `Reader` when `getReader()` method is called.
2. **EVENT SOLUTION** let `SerialPort.readable` or `SerialPort` emit some kind of event ('ready', 'data' etc.) that would allow to call `reader.read()` only in case when there actually is anything to read, or even handle the data in an entirely different mode: such as, for instance establishing event listener `readable.on('data', (chunk) => { ... })` like in NodeJS. In this kind of situations, the application would not read the port in infinite loop (as shown in the API examples, currently the only possibility) but would simply add event listener to the respective event. Maybe I did not go through `ReadableStream` docs deep enough, but I did not find such event (isn't that strange?).

Apparently, the original concept of streams in a web browser, where the stream origin always controls when the stream ends or is closed, does not fit very well to Serial Web API. In some sense this problem is similar to the "issue" of security context, where, for local serial port, remote, network origin (_https://..._ other than _localhost_) IMHO should be considered less, rather than more secure than local origin (_http://localhost_ or _file://..._), which is the opposite of the Secure Context concept for network resources vs. local system environment. Well, not absolutely, but I hope you see the idea.

**Comment by reillyeon** [comment]
The solution to this is documented in [Example 7](https://wicg.github.io/serial/#example-7) in the specification, reproduced here:

```js
let keepReading = true;
let reader;

async function readUntilClosed() {
  while (port.readable && keepReading) {
    reader = port.readable.getReader();
    try {
      while (true) {
        const { value, done } = await reader.read();
        if (done) {
          // |reader| has been canceled.
          break;
        }
        // Do something with |value|...
      }
    } catch (error) {
      // Handle |error|...
    } finally {
      reader.releaseLock();
    }
  }

  await port.close();
}

readUntilClosed();

// Sometime later...
keepReading = false;
reader.cancel();
```

Calling `reader.cancel()` causes the call to `reader.read()` to return immediately, exiting the inner loop and calling `reader.releaseLock()`. The outer loop then exits because `keepReading` has been set to `false` and with the stream unlocked `port.close()` can complete successfully.

Let me know if this example works for you. You can see it in action in [the serial terminal demo](https://github.com/GoogleChromeLabs/serial-terminal/blob/master/src/index.ts)'s implementation of `connectToPort()` and `disconnectFromPort()`. This demo reuses the variable holding the `SerialPort` instance itself instead of a separate boolean which, to be honest, is the less readable approach.

A note which might be of interest to @domenic and @ricea is that this has the side effect of executing the cancel algorithm on the ReadableStream's underlying source. This may not be desirable and this could be an opportunity for an AbortSignal to be passed to `read()` and offer the behavior of only dequeuing the read request without erroring the stream.

**Comment by radio-miskovice** [comment]
So far it doesn't work, but my code is very primitive:
```javascript
// global variables

let spiderInput ;
let readyToClose = false ;

/**
 * Spider Keyer reading loop
 * Continually reads data from serial port.
 * Global variable (keepReading == true) enables the reading loop, otherwise the function returns
 * Reader object is available in global variable spiderInput, to give the app
 * a chance to terminate reading by calling spiderInput.cancel()
 * Otherwise it would be impossible to break the read() method
 */
async function spiderReadLoop() {
  while (spiderKeyer && spiderKeyer.readable && keepReading) {
    spiderInput = spiderKeyer.readable.getReader()
    readyToClose = false
    try {
      while (true) {
        const { value, done } = await spiderInput.read()
        if (done) break;
        else {
          processSpiderData(value)
        }
      }
    }
    catch (e) {
      console.log(e)
    }
    finally {
      spiderInput.releaseLock()
      readyToClose = true
    }
  }
}

/**
 * Disconnect the port and modify GUI accordingly
 * @param {DOMEvent} e 
 */
async function disconnectPort (e) {
  connected = false
  showSpeedButtons(false)
  keepReading = false  // tell the reading loop to terminate on the next event
  spiderInput.cancel() // this should break the reading loop
  // after cancel(), readable stream should be unlocked and ready to close
  // TODO: check if we need to wait for readyToClose or not
  await spiderKeyer.close() // --> throws exception Failed to execute 'close' on 'SerialPort': Cannot cancel a locked stream
  readyToClose = false
  e.target.innerHTML = 'Connect'
  e.target.onclick = connectPort
  spiderStatusLabel.innerText = '(not connected)'
}
```

I think there are two possible solutions:
1. call `spiderKeyer.close()` in the reading loop. This would make sure that the stream is unlocked but on the other hand if the close() failed, disconnectPort() would have no chance to handle that properly.
2. in `disconnectPort()` create a Promise into a global variable, and await it resolve; after `spiderInput.releaseLock()` in spiderReadLoop() if the global variable was a valid promise, it would call resolve().

But I have to think about it. I am not very proficient in synchronizing this kind of stuff.

**Comment by radio-miskovice** [comment]
I don't know how to synchronize between `spiderReadLoop` and `disconnect` :(

When I try something like 
```javascript
//global
let readyToClose ;


async function disconnectPort (e) {
  ...
  keepReading = false  // tell the reading loop to terminate on the next event
  readyToClose = new Promise( resolve => resolve() )  
  spiderInput.cancel() // this should break the reading loop
  await readyToClose
  await spiderKeyer.close() // --> throws exception Failed to execute 'close' on 'SerialPort': Cannot cancel a locked stream
  ...
}

async function spiderReadLoop() {
...
    finally {
      spiderInput.releaseLock()
      if( readyToClose instanceof Promise ) readyToClose.resolve()
    }
  }
}
```
it will not work because the `readyToClose` promise is resolved immediately in `disconnectPort(e)` and does not depend on what `spiderReadLoop()` will actually do.
It seems that this will not help much. Is there any asynchronous action or promise of `SerialPort.readable` or the `Reader` that could be tested in `disconnectPort()`?
I am thinking of another loop calling nextTick() in each iteration and then testing readyToClose (as boolean global variable) or something like that. I tried all possibilities that I know but still can't get reliable and controlled disconnect.

**Comment by radio-miskovice** [comment]
OK, final solution...
Your example was basically right, but the key information was not revealed by the example.

`Reader.cancel()` returns promise!

So in fact the solution is very simple (refer to my first example above):

```javascript
async function disconnectPort (e) {
   ...  // GUI stuff
  await spiderInput.cancel() // this will break the reader and continue after cancel is finished
  await spiderKeyer.close() 
...
}
```

**Comment by radio-miskovice** [comment]
P.S. the information that cancel() returns a promise is almost hidden in the [docs of ReadableStreamDefaultReader](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultReader). The summary page does not mention that cancel() returns a promise, it is only revealed after you click on the header and open [the detail](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultReader/cancel). My first impression was that cancel() must be synchronous method because all other methods return promises, while here it is not mentioned. Do you know who is to be addressed to fix this in MDN? It is confusing.

**Comment by reillyeon** [comment]
@jpmedley, can you update the documentation of ReadableStreamDefaultReader's cancel() method to say in the top-level description that it returns a Promise?

**Comment by jpmedley** [comment]
PR here: https://github.com/mdn/content/pull/2257
