### ISSUE TITLE
Please add another example to API docs

### ISSUE THREAD

**Issue by radio-miskovice** [WICG/serial#113]
It will save people working with the serial port lot of time :-)
See [issue 112](https://github.com/WICG/serial/issues/112)

**Comment by reillyeon** [comment]
I think it would be sufficient to update [example 7](https://wicg.github.io/serial/#example-7) to await reader.cancel() before calling port.close(). Is there anything else you'd like to see in that example?

**Comment by radio-miskovice** [comment]
I think what you propose is sufficient.

**Comment by reillyeon** [comment]
Thanks for the feedback. I was going to add another example showing that the,

```js
await reader.cancel();
await port.close();
```

pattern is a valid option but realized that there is a good reason to put `await port.close()` after the loop instead so I clarified the existing example rather than adding a new one.
