### ISSUE TITLE
reader.cancel() example on web.dev makes no sense.

### ISSUE THREAD

**Issue by marciot** [WICG/serial#126]
I am trying to unsuccessfully fix some errors in my code regarding closing ports and I believe it stems from my general confusion with stream locking.

To try to get a better handle on things, I am looking at the example from [this page](https://web.dev/serial/):

```
// Without transform streams.

const reader = port.readable.getReader();

// Listen to data coming from the serial device.
while (true) {
  const { value, done } = await reader.read();
  if (done) {
    reader.releaseLock();
    break;
  }
  // value is a Uint8Array.
  console.log(value);
}

// Force reader.read() to resolve immediately and subsequently
// call reader.releaseLock() in the loop example above.
await reader.cancel();
await port.close();
```

The line "await reader.cancel()" make no sense. According to the comment, it forces the "reader.read()" to resolve immediately, but I do not understand this; the only way to reach that line of code is for the "await reader.read()" to exit so that the code can break out of the loop, which means the "reader.read()" is *already* resolved. So I do not understand what that example is getting at when they call "reader.cancel()"

That line seems superfluous to me. In general, I do not understand under which situation "reader.cancel()" may be useful, unless you are doing some sort of concurrent execution. I assume that if you write a single execution thread using async/await, you should *never* need "reader.cancel()". Is this a correct assumption?

-- Marcio

**Comment by marciot** [comment]
On a similar vein:

```
const reader = port.readable.getReader();

// Listen to data coming from the serial device.
while (true) {
  const { value, done } = await reader.read();
  if (done) {
    // Allow the serial port to be closed later.
    reader.releaseLock();
    break;
  }
  // value is a Uint8Array.
  console.log(value);
}
```

Under what circumstances would anyone want to call "reader.releaseLock()" anywhere other than immediately preceding a "serial.close()"? It would seem like the most sensible thing to do is to create a reader and a writer as soon as you open the port and to release them when you are done with the serial port, just prior to closing the port. Am I missing a situation in which it may be desirable to do otherwise?

**Comment by reillyeon** [comment]
If you add some console logging to the code above you can see the order in which it is executed:

```js
const reader = port.readable.getReader();

// Wrap the loop in an immediately invoked async function so that execution continues to the lines below. In a
// real application they would be in something like a 'click' event handler. 
(async function() {
  while (true) {
    const { value, done } = await reader.read();
    console.log("1");
    if (done) {
      reader.releaseLock();
      break;
    }
    // value is a Uint8Array.
    console.log(value);
  }
})();

await reader.cancel();
console.log("2");
await port.close();
console.log("3");
```

This prints,

```
1
2
3
```

The reason this happens is that each line after an `await` is essentially its own function which is passed to the `then()` method of the `Promise` being awaited. `reader.cancel()` causes the `Promise` returned by `read()` to be resolved before the `Promise` that it itself returns is resolved and so the code inside the loop gets to execute first and unlocks the stream before `port.close()` is reached.

@beaufortfrancois, the example on web.dev could probably be clarified. In the version of this example [from the specification](https://wicg.github.io/serial/#example-7) I make it clearer that these two sections of code aren't in the same function. I also use a slightly different pattern which handles errors better.

**Comment by marciot** [comment]
@reillyeon: That is what I thought. However, it is true that the "await reader.cancel()" is not doing anything, if this is taken to be one function, because the reader is *not* blocked anymore. Correct?

**Comment by reillyeon** [comment]
Correct, if the example were interpreted as a single function calling `reader.cancel()` at the end of the loop is a no-op (actually, it would throw an exception since `reader.releaseLock()` was called) because the stream is already closed if `read()` returned with `done` set to `true`. You can see that in `readUntilClosed()` [from the specification example](https://wicg.github.io/serial/#example-7) where I only call `reader.releaseLock()` in the `finally` clause before calling `port.close()`.

**Comment by marciot** [comment]
@reillyeon: Thank you for the clarification. 

In your example, did you mean for there to be an "await" in the line "const closed = readUntilClosed()"?

Without that, it is my understanding the loop would run concurrently to the rest of the code that follows, so the "cancel()" would, in fact, do something.

This sort of concurrency is something I am actively avoiding in my own code, however. I am keeping my serial operations in one execution path and using "await" for every "async" function call. In fact, I would love it if Javascript could warn you when you left a "await" out when calling a "async" function. It would have saved me a few headaches.

**Comment by reillyeon** [comment]
The lack of an `await` on that line is intentional. We wait to await that `Promise` until the last line.

The intention is to allow the loop in `readUntilClosed()` to run interleaved (not true concurrency) with any other code on the page. That includes, for example, code which might be writing to the device, handling UI input, or eventually calling `reader.cancel()` so we can close the port.

**Comment by marciot** [comment]
@reillyeon: Oh. Wow. I see it now. I am both impressed and terrified by how powerful modern Javascript can be. It's come a long way from the callback hell of the early days.

**Comment by reillyeon** [comment]
Assigning this to François to improve the documentation on web.dev to make the design pattern we're suggesting clearer.

**Comment by marciot** [comment]
I now see that this pattern makes sense because the loop never ends and it is presumably started by a script at page load that you don't want to interrupt. I didn't have to use that pattern because my situation is a bit different. Both operations I am doing, flashing firmware and printing to the 3D printer, require the user to click a button to initiate and the operation naturally end on it's own sometime in the future.

I guess the only thing I failed to deal with is if the user tries to start both operations at once. Ooops. I better go take care of that possibility.

**Comment by beaufortfrancois** [comment]
Thank you both for improving the article. I've filed https://github.com/GoogleChrome/web.dev/pull/4776.

**Comment by reillyeon** [comment]
Thanks Francois for updating the article. Closing this issue.
