### ISSUE TITLE
Serial': "Must be handling a user gesture"

### ISSUE THREAD

**Issue by Akhila-git** [WICG/serial#131]
Hi, 
 For my application I am reading from a weighing scale connected to USB using RS232-USB converter. 
I am trying to read from a serial port, 
when I execute the following code , 
navigator.serial.requestPort({  }) I get error 

**There was an error opening the serial port: DOMException: Failed to execute 'requestPort' on 'Serial': Must be handling a user gesture to show a permission request.**

It will work if it is part of a button click event.

Would the seamless integration be possible? A serial port is connected once I log in and from any where in the application, I should be able to call my function getWeight() that will  read from the serialport
regards,
Akhila

**Comment by reillyeon** [comment]
`requestPort()` is designed to be called during a "setup" phase where you get consent from the user to access their device. Once you have permission you can connect to the port immediately but you can also call `getPorts()` later to get a list of the ports that the user previously granted your site access to. This is how you get the seamless integration you are looking for.

Note, there are some cases where the browser cannot reliably determine, after an application or system restart that the currently connected device is the same one that the user previously selected and so there are cases where a call to `requestPort()` will always be required. These are browser bugs which may eventually be resolvable with further study of the devices in question.

**Comment by sandipkumarnandi** [comment]
I have a typical issue, where the requestPort() is throwing the below error "There was an error opening the serial port: DOMException: Failed to execute 'requestPort' on 'Serial': Must be handling a user gesture to show a permission request"

First time it did asked via a popup, after that it did not worked

**Comment by reillyeon** [comment]
requestDevice() must always be called with a user gesture. If you are trying to reconnect to a port the user has already granted the site access to you can call getPorts() and open() without a user gesture.
