### ISSUE TITLE
Add a forget() method to voluntarily revoke permission

### ISSUE THREAD

**Issue by reillyeon** [WICG/serial#132]
Some sites may not be interested in retaining long-term permissions to access a USB device. For example, for an educational application that is being used on a shared computer with many devices a large number of accumulated permissions creates a poor user experience. In addition to user agent mitigations to avoid this problem, such as defaulting to a session scoped permission on the first request or expiring infrequently used permissions, it should be possible for the site itself to clean up permissions it is no longer interested in retaining.

**Comment by enok71** [comment]
It should definitely be possible to undo requestPort for a specified port, or for all ports.
