### ISSUE TITLE
Allow stream reader cancel() method to return bytes from queue instead of discarding them.

### ISSUE THREAD

**Issue by DarDoro** [WICG/serial#146]
There are no benefits from returning {value: undefined, done: true} after "cancel()" and discarding already received bytes.

Returning {value: byes_read_so_far, done: true} will act much better, allowing to implement timeout and preserving data.
Also, "cancel()" implemented this way will be compatible with the current implementation. When done=true, "readable" will be unlocked. For "value" not eq. "undefined" the last chunk will be reliable processed.
It's possibly the "lowest hanging fruit" for many similar requests.
It will partially fulfill other requests eg. #1103
whatwg/fetch#180

**Comment by reillyeon** [comment]
I'm going to reopen the Streams API version of this issue because the behavior of the `cancel()` method is not defined by the Web Serial API.
