### ISSUE TITLE
Consider redirecting https://reillyeon.github.io/serial/

### ISSUE THREAD

**Issue by domenic** [WICG/serial#147]
My browser address bar keeps autocompleting it :).

The separate repo at https://github.com/reillyeon/serial might cause similar confusion.

See https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7 for one technique if you want to delete your fork, or you could just update the index.html if you want to keep it.

**Comment by reillyeon** [comment]
I've turned off GitHub Pages for my fork so it should 404, which I think is the best option for forks. That should get your browser to stop auto-completing it but if it doesn't you can click the little "x" on the right-hand side of the suggestion and it should stop.
