### ISSUE TITLE
chrome serial device added not working.

### ISSUE THREAD

**Issue by jskorlol** [WICG/serial#153]
1. In chrome Dev and Canary, as below. Serial device added is normal.
![image](https://user-images.githubusercontent.com/12728472/145686729-eed25e14-b25b-4d41-aae8-ef026ac953bf.png)

2. However, in general chrome, serial device is not added.
![image](https://user-images.githubusercontent.com/12728472/145686747-11ffd63c-17c9-4592-88e5-a8f261d89104.png)

3. In general, I enabled the enable-experimental-web-platform-features option.

Is serial device added not automatically added in regular chrome yet?

We confirmed that dev, canary, and general are all enabled as USB. Only serial is missing.

Is there any setting I'm missing?

**Comment by reillyeon** [comment]
There is [one recent change](https://chromium-review.googlesource.com/c/chromium/src/+/3256942) to serial port enumeration which hasn't made it into Chrome stable-channel yet. You can try beta-channel to see if this is indeed where the change in behavior you are observing is introduced.

The `enable-experimental-web-platform-features` flag is not required to use the Web Serial API.

Note that serial device enumeration is not enabled until a site requests serial ports (either via `navigator.serial.requestPort()` or `navigator.serial.getPorts()`) and so on any Chrome version you won't see serial ports logged until one of these APIs is called. USB device enumeration on the other hand is enabled at Chrome startup.

**Comment by jskorlol** [comment]
Oh, I checked, I'll wait. thank you :)
