### ISSUE TITLE
Introduction should mention virtual serial ports 

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/serial#16]
The introduction of the spec (or the use cases) section should mention virtual serial ports provided by both Bluetooth and by USB. 

What to basically capture what is here:
https://www.dropbox.com/s/zrz5r2klweg0fq4/webserial%20vs%20webusb.png

**Comment by Fleker** [comment]
I'm curious as to how this spec will work on Raspberry Pis. A Raspberry Pi can run a web browser with a web app, but has exposed I/O to directly interface with a serial device using the UART bus.

**Comment by reillyeon** [comment]
Built-in UARTs will also be supported.

**Comment by reillyeon** [comment]
Virtual serial ports are now covered in the explainer and are mentioned in the security considerations section.
