### ISSUE TITLE
Web Serial API cannot access client ports issue

### ISSUE THREAD

**Issue by vigor45** [WICG/serial#163]
Im trying to use Web Serial API to communicating with serial ports in a local machine. it works fine even hosted in local IIS. But it doesn't work when run from a server. JavaScript is client side language so why this difference? is there anyway to correct this by giving some privileges by changing below script ? or is there some more chrome experimental features to achieve this ? Thanks.

**Comment by larsgk** [comment]
> Im trying to use Web Serial API to communicating with serial ports in a local machine. it works fine even hosted in local IIS. But it doesn't work when run from a server. JavaScript is client side language so why this difference? is there anyway to correct this by giving some privileges by changing below script ? or is there some more chrome experimental features to achieve this ? Thanks.

When you run from the server, have you made sure the app is hosted using HTTPS and there is a valid certificate?

**Comment by larsgk** [comment]
@vigor45 - try to look here (related to secure contexts): https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features/

**Comment by reillyeon** [comment]
Please re-open this issue if you can provide more details about your environment and the error you are encountering. At this moment this issue report is unactionable.

**Comment by vigor45** [comment]
> > Im trying to use Web Serial API to communicating with serial ports in a local machine. it works fine even hosted in local IIS. But it doesn't work when run from a server. JavaScript is client side language so why this difference? is there anyway to correct this by giving some privileges by changing below script ? or is there some more chrome experimental features to achieve this ? Thanks.
> 
> When you run from the server, have you made sure the app is hosted using HTTPS and there is a valid certificate?

It works. Thanks!
