### ISSUE TITLE
Need to specify hardware/software flow controls

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/serial#17]
@voodootikigod  wrote [elsewhere](https://groups.google.com/d/msg/mozilla.dev.webapi/wykkibp6BKo/VI0Z9Bm7mkgJ): 

> Yes WebSerial doesn't need a massive API, but there are some key things that are missing from the list for things like hardware/software flow controls and handling of the various options. 

@voodootikigod, can you please provide more details.

**Comment by kenchris** [comment]
@sangwhan

**Comment by reillyeon** [comment]
Closing this issue in favor of #157 and #176.
