### ISSUE TITLE
The navigator. Serial. RequestPort () can't get the usb link equipment

### ISSUE THREAD

**Issue by 954514762** [WICG/serial#194]
![image](https://github.com/WICG/serial/assets/54922832/cee0067d-4fbe-4af4-b8c5-435a271ee4b0)
HelloSerial.html:1  Uncaught (in promise) DOMException: Failed to execute 'requestPort' on 'Serial': No port selected by the user.

**Comment by reillyeon** [comment]
Check in `edge://device-log` to see if the serial device has been detected, then check in the Windows Device Manager control panel to make sure that the device has been installed correctly and has a COM port number (e.g. COM3).

**Comment by 954514762** [comment]
There are all of them. I'll see if there are any examples of the whole project

**Comment by reillyeon** [comment]
Can you provide screenshots of the logs showing the devices being detected?

**Comment by reillyeon** [comment]
Closing due to lack of response.
