### ISSUE TITLE
Do databits and stopbits need to be restricted?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/serial#21]
`databits` is currently restricted to: 8, 7, 6, or 5; and `stopbits` to: 1, 2. 

Are there any use cases for allowing any different values for the above? 

If not, I will change the above to enums in the spec.

**Comment by reillyeon** [comment]
The permissible values for `dataBits` and `stopBits` are limited by what is actually permitted by hardware implementations as well as operating systems. The currently specified restriction limits `dataBits` to 7 or 8 and `stopBits` to 1 or 2 without making these enums. These ranges could be expanded (e.g. to support 5 or 6 database, or 1.5 stop bits) but this needs to be done carefully given that these modes are not universally supported.
