### ISSUE TITLE
Need use case for USB, BlueTooth, RS232

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/serial#23]
As described in https://github.com/whatwg/serial/issues/19, the currently supported device types are USB, BlueTooth, RS232. This needs to be generalized into a use case and set of requirements.

**Comment by larsgk** [comment]
Given that we now will get WebBluetooth and WebUSB (hopefully), I think it will make good sense to check if (web)serial will be working on top of those.  Maybe this is already the plan?

**Comment by tzikis** [comment]
@larsgk actually, I would argue that we shouldn't. The OS already gives APIs for accessing serial ports in a common interface, regardless of whether they are virtual (Bluetooth, USB) or physical (RS232) serial ports

Let me put it another way. The OS has drivers that make Bluetooth and USB devices appear as Serial devices, which work perfectly well and in a consistent manner, so it becomes simply. So WebSerial should be complimentary to WebBluetooth/WebUSB, not built on top of them.

**Comment by fbender** [comment]
Indeed. That is what we established long before. Apart from missing out on other serial interfaces, there are different security implications for both USB und Bluetooth. For prototyping or prollyfilling the API, both could (theoretically) work, though.

**Comment by reillyeon** [comment]
Use cases and motivation for this API are provided in the explainer.
