### ISSUE TITLE
What's the use case for `pnpId`? 

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/serial#26]
Microsoft [states](http://msdn.microsoft.com/en-us/library/windows/hardware/gg463195.aspx) that: 

> Note: For PCI, PC Card, USB, and IEEE 1394 devices, Vendor IDs are assigned by the industry standards body and must be used instead of the Plug and Play IDs described in this article.

Given the above, it doesn't strike me like a good idea for the API to rely on a proprietary Microsoft thing - unless there is a valid use case for it.

**Comment by reillyeon** [comment]
Closing this issue as suggested by Jay. `getInfo()` as currently specified provides the vendor and product IDs (for USB devices) and we can separately debate the value of adding other standard USB strings such as product, manufacturer and serial number vs. the fingerprinting risk in other issues. Exposing the raw PnP ID is unnecessary and Windows-only to boot.
