### ISSUE TITLE
API differences with NodeJS streams-based api design

### ISSUE THREAD

**Issue by JayBeavers** [WICG/serial#30]
I've posted a simple sample, roughly equivalent to the example in this spec, to a branch of node-serialport at:

https://github.com/JayBeavers/node-serialport/blob/apiProposal/docs/apiProposal.md

I wanted to highlight the potential differences between what we're working on here and what a very similar API would look like following NodeJS conventions.

The biggest thing to call out at first is that the SerialPort object would inherit from DuplexStream, so rather than having:

whatwgport.in.read(...);
whatwgport.out.write(...);

we'd have

nodeport.on('read', ...); // or nodeport.read(...);
nodeport.write(...);

I'll work towards implementing a simple wrapper over node-serialport that exactly implements this proposed nodejs API to help move this discussion forward.

I also added serialPortDetails.open(options) which is semantically equivalent to calling new SerialPort(serialPortDetails.path, options).

**Comment by reillyeon** [comment]
Closing this issue as we have decided to remain consistent with Web Platform design principles and use the Streams API.
