### ISSUE TITLE
Don't allow enumeration of serial ports (or do it separately).

### ISSUE THREAD

**Issue by fbender** [WICG/serial#4]
As written on the [mailing list post](https://groups.google.com/forum/#!topic/mozilla.dev.webapi/wykkibp6BKo): 

<blockquote>
<p>A: getPorts() would allow fingerprinting, IMO. The severity depends on when you want to allow access to the API (e. g. when `navigator.connectSerialPort()` [1], that reduces fingerprinting to users who opt in; whereas when prompting the user upon the first data received via serial port[2] and allowing to query all available ports, that allows straight fingerprinting.</p>

<p>B: Selecting the port to talk to should be up to the UA (mitigating A), listing the available ports (e. g. with a LRU list at the top) with the permission prompt […], i. e. a getPorts() method is not necessary. The API should allow a mechanism to connect to multiple devices […] </p>
</blockquote>

So, **tl;dr**, with additional thoughts not covered above: 
- `getPorts()`/`requestList()` allows fingerprinting, a no-no. 
- Once you grant access to the API, and you are not restricting access on a port-by-port basis, a script can go rogue (intentional or not, doesn't matter) enumerating and connecting to all devices it can find. Bad for the user, and restricting API adoption (browser vendors may not like that functionality).
- The user should select the port to connect to (maybe using LRU and displaying some hardware information like manufacturer and pnpId where appropriate to aid the user in selecting the right port). 
- The problem is with non-UI environments like node – they need a port enumeration feature. Is this out-of-scope for the spec? If not, can this be made a separate API that is optional to implement or requires further privileges (e.g. via a separate prompt <-- bad UX, or chrome/elevated privileges).

**Comment by reillyeon** [comment]
In #105 I've specified both a `getPorts()` method and a `requestPort()` method, with language describing how `getPorts()` only returns ports which the site has been previously granted access to. This needs to be further clarified (this is tracked by #107) but the overall approach is similar to the principles expressed in the summary of this issue. Ports should not be generally enumerable. The user should be allowed to select only the port that is relevant to the site they are visiting.

Managed or embedded environments (such as kiosk-mode web application or Node.js application) may extend this model by predefining a set of ports that would be returned by `getPorts()`, perhaps making `requestPort()` completely unnecessary in their very particular environments.
