### ISSUE TITLE
Transfer to WICG

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/serial#45]
A few folks would like to do some incubation work on this:
https://discourse.wicg.io/t/serial-api-moving-from-web-of-sensors-cg-to-web-incubator-cg/

Could someone at the WHATWG please transfer ownership of it to the WICG? If it makes progress and gets traction, we can then find an appropriate home for it (either back here or somewhere in the W3C).

**Comment by marcoscaceres** [comment]
Cc @whatwg/sg

**Comment by sideshowbarker** [comment]
I have the necessary github perms for both orgs, so I’m happy to do the transfer. But not sure who needs to OK it first

**Comment by marcoscaceres** [comment]
It's C0, and I did all the editing on it. So if we transfer it, and folks want to continue to work on it under the WICG license, then we can get them to sign the W3C CG agreement.

**Comment by marcoscaceres** [comment]
Ok, I've added this to the W3C repository manager. It will now do IPR checks. 

Folks following who are going to participate, if you haven't already please sign up to the WICG by clicking "join this group" at https://www.w3.org/community/wicg/

**Comment by marcoscaceres** [comment]
@reillyeon I've made you repo admin.
