### ISSUE TITLE
Issues with respec (and markdown?)

### ISSUE THREAD

**Issue by kenchris** [WICG/serial#58]
All sections seems to be considered informative which causes issues though these sections are created using markdown and not with id="informative"

![image](https://user-images.githubusercontent.com/1101339/53807383-b9949700-3f4f-11e9-8e47-2d5c7d8c09e0.png)

**Comment by marcoscaceres** [comment]
Ah, will fix tomorrow. Thanks for catching that.

**Comment by marcoscaceres** [comment]
Just adding a `<section id=conformance></section>` somewhere near the end should fix that. ReSpec can’t treat specs as normative without that.

**Comment by reillyeon** [comment]
The [STREAMS] reference now appears to be properly normative.
