### ISSUE TITLE
Issue with respec: backtick not turned into <code> in tables

### ISSUE THREAD

**Issue by kenchris** [WICG/serial#59]
![image](https://user-images.githubusercontent.com/1101339/53808560-de3e3e00-3f52-11e9-88fd-05c9eb19eb60.png)

**Comment by marcoscaceres** [comment]
For security reasons, that’s no longer supported by the library that processes the markdown: we are now using Github flavoured markdown (which doesn’t support that either in tables unfortunately).

**Comment by kenchris** [comment]
So just change these to `<code>` then?

**Comment by marcoscaceres** [comment]
Yep

**Comment by marcoscaceres** [comment]
I’ll help with the other PR you sent. Spotted a few little things. Happy to jump in there and fix up stuff.

**Comment by kenchris** [comment]
OK done that in my PR

**Comment by kenchris** [comment]
> I’ll help with the other PR you sent. Spotted a few little things. Happy to jump in there and fix up stuff.

Ah great, please tell me and I can fix :-)
