### ISSUE TITLE
Are productId and vendorId specific to serial over USB?

### ISSUE THREAD

**Issue by kenchris** [WICG/serial#62]
https://github.com/w3ctag/design-reviews/issues/431

Would be great to fill out the description part of the metadata table

**Comment by larsgk** [comment]
I don't know of any other (than USB) using VID/PID (2x16bit) values for initial ID.  I'm assuming you are considering other kinds of access like old school serial port, bluetooth or other?

**Comment by larsgk** [comment]
Actually, having the very USB specific values in the metadata table, where USB (strictly) is not related to the serial connection part, should leave room for other types of HW connectivity identifiers (BT MAC?)

**Comment by reillyeon** [comment]
USB and Bluetooth have the concept of vendor and product IDs and I think that's useful for developers targeting a device from a manufacturer that has customized these IDs. There will of course also be ports for which these IDs aren't available or meaningful because it is a generic converter or a built-in port.

**Comment by neurobe** [comment]
In my use case, I have common VID and PID across a range of products and, in the case of WebUSB usage, target the serial number to differentiate the products. It was done this way to simply Windows driver requirements.
So my vote is for completing the serial port meta data table as much as possible, when possible.

**Comment by reillyeon** [comment]
Wherever vendor and product ID are currently mentioned in the specification it is made clear that they are specific to serial over USB. If specific support (such as filtering) where implemented for Bluetooth or another class of devices then similarly specific properties will be added.
