### ISSUE TITLE
Should in/out be reader/writer instead?

### ISSUE THREAD

**Issue by kenchris** [WICG/serial#63]
https://github.com/w3ctag/design-reviews/issues/431

That seems a bit more common with the streams API. Any take @domenic ?

**Comment by domenic** [comment]
They should be readable/writable. https://github.com/whatwg/streams/issues/174

**Comment by FanatiQS** [comment]
This information should be updated in the example available at line 38 in index.html to not confuse. Took me a little while to understand that in was the same as readable.

**Comment by domenic** [comment]
Bump on this issue; the spec and explainer still use in/out, and it'd be good to align these with other "paired streams" on the platform.

I'm happy to work on adding more explicit guidance on this to the Streams Standard if that'd be helpful.

**Comment by reillyeon** [comment]
The explainer and Chromium prototype use readable/writable. I am working on a new revision [here](https://reillyeon.github.io/serial) which includes this and many other changes.

**Comment by domenic** [comment]
Ah, great, OK! And sorry for the confusion; I misremembered one of the spec examples as being an explainer example.

**Comment by reillyeon** [comment]
This was fixed by #105.
