### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by Keavon** [WICG/serial#65]
Hello, I do not have any comments to add but I wanted to ask what the status of this API proposal is. Things seem to have gotten quiet after a few months. I am very, very excited for this API to be added to Chromium, hopefully in the near-ish future. How far does the definition stage need to go before it can begin the implementation phase?

**Comment by reillyeon** [comment]
The implementation phase is in progress in the Chromium project. Follow [issue 884928](https://bugs.chromium.org/p/chromium/issues/detail?id=884928) and the issues it is blocked on for updates. This specification is being developed under the WHATWG working mode and so there needs to be an implementation before specification changes can be merged.
