### ISSUE TITLE
Do not limit baudrate selection to enumerated values

### ISSUE THREAD

**Issue by vrabcak** [WICG/serial#66]
There are many serial ports which allows arbitrary baudrate selection, especially higher than 115200. (e.g. PL-2303HX allows baudrate up to 6000000).

There was even use-cases for arbitraty baudrates in #11 of this speciffication but it seems to be forgotten :-)

**Comment by reillyeon** [comment]
The use cases were added to the specification but the list of allowed values for the `baudrate` option was not removed. I plan on removing this restriction as there are clear use cases for arbitrary values. The prototype implementation in the Blink engine does not place restrictions on baud rate.

**Comment by kenchris** [comment]
Please do, we ran into this in the TAG review as well as the values contradicted the text. 

But you could list then in a note as common values.

**Comment by ForbiddenEra** [comment]
+1

Arbitrary would be great; at the minimum standard rates up to 921600 as a minimum - basically any FTDI chip can do this and that will be very common use case (interfacing with any device with an FTDI, eg, Arduino, car ECUs, etc)

I did try 230,400 in Chrome current and nothing complained; haven't reviewed the actual implementation there to see if it follows the spec or not, but while the spec is open I thought I'd comment so it's known it's wanted.

**Comment by reillyeon** [comment]
This was fixed by #105.
