### ISSUE TITLE
Consider using a generic Event

### ISSUE THREAD

**Issue by reillyeon** [WICG/serial#73]
The proposed WebIDL for this API includes a SerialConnectionEvent. The TAG design principles [suggest](https://w3ctag.github.io/design-principles/#state-and-subclassing) using a generic event and storing state in the `target` attribute. This change would require moving the `connect` and `disconnect` event handler attributes to the `SerialPort` interface and defining that events bubble from `SerialPort` instances to the singleton `Serial` instance.

**Comment by domenic** [comment]
I think this advice isn't as applicable here, because the `port` is not itself an `EventTarget`, and thus cannot be the target of the event. A custom event subclass seems very reasonable for this case.

**Comment by reillyeon** [comment]
This was fixed by #105.
