### ISSUE TITLE
Example 1 Uses Wrong SerialOptions object

### ISSUE THREAD

**Issue by odejesush** [WICG/serial#82]
The first example, [Requesting an Arduino device], is creating a [`SerialOptions`] object with a `filters` property. However, the IDL for [`SerialOptions`] does not have this property. The example should be updated to reflect the current shape of the dictionary to prevent confusion. This was pointed out in [Issue 1067579].

[Requesting an Arduino device]: https://wicg.github.io/serial/#example-1-requesting-an-arduino-device
[`SerialOptions`]: https://wicg.github.io/serial/#serialoptions-dictionary
[Issue 1067579]: https://crbug.com/1067579

**Comment by bus710** [comment]
Same here.
I am using Chrome 81.0.4044.92 on Ubuntu x64.
Unlike the document, requestPort accepts serialport options not filter options.

**Comment by reillyeon** [comment]
This was fixed by #105.
