### ISSUE TITLE
Problem with websersial with my web served on a server when I access from another machine

### ISSUE THREAD

**Issue by dvalladaresv** [WICG/serial#83]
Hello,

I put my situation in context:

I have a small example with webserial for arduino, when I raise my website from a server and access it from the machine that serves it, it works perfectly (localhost: <port>). But if I access this server (ip_server: port) from another machine, I get the error => TypeError: Cannot read property.

I have in the code also added, so that it detects if serial is allowed in the browser and if it is not, it shows a message, and it also happens that when accessing from another machine, it is as if it did not recognize webserial:

if ('serial' in navigator) {
     const notSupported = document.getElementById ('notSupported');
     notSupported.classList.add ('hidden');

   }

Thank you for your collaboration, I am sorry if I have not explained correctly.

**Comment by reillyeon** [comment]
The Serial API is only exposed in "secure contexts" which means localhost or HTTPS. The `navigator.serial` property will be `undefined` if the page is loaded over HTTP.

**Comment by dvalladaresv** [comment]
Thank you very much for the reply

sincerely!
