### ISSUE TITLE
Buffer not draining

### ISSUE THREAD

**Issue by spekary** [WICG/serial#84]
I am doing a series of reads and writes to the SiliconLabs CP210x UART bridge driver.

1) It looks like the readable and writable are sharing the same buffer. Sometimes when I write, and then read, what I wrote earlier is showing up at the beginning of the read stream.
2) After a while, read stalls. If I increase the size of the buffer at serial.open() time, then I can read more data, but it eventually stalls as well. The only way around this appears to be either to set the buffer to the size of all anticipated data, or to open and close the serial port between read and write operations, but this really, really slows things down.

Expected: Reading from the readable should make room in the buffer for more read operations.

**Comment by reillyeon** [comment]
This sounds like a Chromium implementation issue (and possibly a driver bug) and not a specification issue. Chromium issues should be reported to [crbug.com](https://crbug.com). Please include details about your platform (Windows? macOS? Linux?) as well as example code to reproduce the issue if possible.
