### ISSUE TITLE
Failed to execute 'requestPort' on 'Serial'

### ISSUE THREAD

**Issue by dvalladaresv** [WICG/serial#85]
Hello,

I write because sometimes the connection to serial is done perfectly but other times it gives me an error in => navigator.serial.requestPort (). Attached image with the error in case you can help me with it.

![image](https://user-images.githubusercontent.com/47456806/80694239-8195cf00-8ad4-11ea-80c3-25f307681ac1.png)

Thanks for the help!

**Comment by svendahlstrand** [comment]
Hello,

As a security measure, `requestPort` must be initiated by a user gesture. Like a button click. You are getting that error because you're calling `requestPort` without a previous user gesture.

Try moving the call inside a button click event handler – or similar.

**Comment by dvalladaresv** [comment]
Thank you very much for the info. My problem was that the button that activated the user did other things and it was a long time before I called an order, then it already failed.
