### ISSUE TITLE
How do we express support?

### ISSUE THREAD

**Issue by computersarecool** [WICG/serial#86]
Hello.  I just wanted to share how great I think this new API is.  I have had a lot of fun exploring it. 

I am wondering if there is anywhere I can express my feelings in the hopes that this becomes a web standard.

I am very much appreciate of the work being done on this and would love to help where I can.

**Comment by reillyeon** [comment]
If you want to express support leave a comment on this [WICG Discourse thread](https://discourse.wicg.io/t/serial-api-moving-from-web-of-sensors-cg-to-web-incubator-cg/2940).

If you would like to help out try out my prototype implementation in Chromium. File issues here if you find any issues with how the API is structured, places where it is awkward and could be improved. File issues on [crbug.com](https://crbug.com) if you think you've found an implementation bug. I monitor the `Blink>Serial` component and can triage the issue.

If you build something cool write a blog post about it or talk about it on social media.
