### ISSUE TITLE
Remove `Serial.getPorts`

### ISSUE THREAD

**Issue by asankah** [WICG/serial#92]
The `Serial` interface ([permalink](https://wicg.github.io/serial/#serial-interface)) defines a very questionable `getPorts` method which arguably should not exist.

Remove?

**Comment by reillyeon** [comment]
Can you elaborate on why you believe this method is questionable?

The specification does not currently provide a recommendation for how `getPorts()` should be implemented. The prototype implemented in the Chromium project currently returns the set of `SerialPort` objects the site has been previously granted permission to access after calling `requestPort()`. This seems like reasonable behavior.

**Comment by asankah** [comment]
Ah. I didn't see any mention of it outside of the IDL for `Serial`.

Questionable because nominally it seems to imply that it exposes the list of ports and does not mention any restrictions about its behavior.

The prototype behavior does sound reasonable. Let's update the spec to match 😄

**Comment by reillyeon** [comment]
The roles of the `requestPort()` and `getPorts()` methods was clarified in #105. Precisely defining the storage model for port permissions is tracked in #107 but the text in the current security and privacy considerations sections should be sufficient to resolve the concern raised here.
