### ISSUE TITLE
Control signals missing in the serial API

### ISSUE THREAD

**Issue by Gamadril** [WICG/serial#99]
The serial API does not contain any information about control signals. However Chrome seems to be able to read (`getSignals()`) and change (`setSignals()`) the state of the control lines. I think it should be part of the specification since using the control lines is useful to toggle some pins of a connected device and read their state .

**Comment by reillyeon** [comment]
In my [fork](https://reillyeon.github.io/serial/) of the specification which I am working on merging back into this draft I have started to document these methods.

**Comment by reillyeon** [comment]
This was fixed by #105.
